#language: rust
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsnappy-dev
install: ./setup.sh
env:
  - LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/ RUST_BACKTRACE=1 PATH="$HOME/.cargo/bin:$PATH"
script:
  - make
  - make tests
  - ./dryad.so.1
#  - test/test
