language: rust
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsnappy-dev
install: ./setup.sh
env:
  - LD_LIBRARY_PATH=/lib/x86_64-unknown-gnu RUST_BACKTRACE=1
script:
  - ./make.sh
#  - ./gen_tests.sh
#  - test/test
  - ./dryad.so.1
