language: rust
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsnappy-dev
install: ./setup.sh
env:
  - LD_LIBRARY_PATH=/lib/x86_64-unknown-gnu RUST_BACKTRACE=1 LD_DEBUG=0
  - LD_LIBRARY_PATH=/lib/x86_64-unknown-gnu RUST_BACKTRACE=1 LD_DEBUG=1
script:
  - ./make.sh
  - ./gen_tests.sh
  - ./dryad.so.1
  - test/test
