[package]
name = "dryad"
version = "0.1.2"
authors = ["m4b <m4b.github.io@gmail.com>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
crossbeam = "0.2.9"
goblin = {git = "http://github.com/m4b/goblin"}
colorify = "0.2.2"

[profile.dev]
panic = "abort"

[features]
default = []
no_color = []
