[package]
name = "dryad"
version = "0.1.2"
authors = ["m4b <m4b.github.io@gmail.com>"]
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
gcc = "0.3"

[dependencies]
crossbeam = "0.2.9"
syscall = "0.2.1"
colorify = "0.2.2"

[features]
default = []
no_color = []

[dependencies.goblin]
git = "http://github.com/m4b/goblin"
default-features = false
features = ["no_mach", "no_mach32", "no_pe", "no_pe32", "no_goblin", "no_endian_fd", "no_elf32"]
